export interface StyleSheet {
    container: any,
    divider: any,
    dividerRight: any,
    dividerRow: any,
    h1: any,
    h2: any,
    h3: any,
    h4: any,
    header: any,
    left: any,
    page: any,
    right: any,
    row: any,
}